In [1]:
import pandas as pd

# Pandas Practice Healthcare Dataset
### Sheryians AI School

You'll be working with a real, messy healthcare dataset (**55,500 rows**) to practice everything from this course loading, inspecting, filtering, cleaning, feature engineering, sorting, and grouping.

**Instructions:**
- There are **12 questions**, arranged from easy to hard.
- Write your answer in the empty code cell right below each question.
- Make sure `healthcare_dataset.csv` is in the same folder as this notebook.
- A couple of questions specifically use `.apply()` — that's intentional, don't skip them!

Good luck 🚀

### Question 1 — Load & Look
Load `healthcare_dataset.csv` into a DataFrame called `df`. Display the first 5 rows and print the shape (rows, columns).

In [34]:
df=pd.read_csv("healthcare_dataset (1).csv")

### Question 2 — Get to Know the Data
Check the data type of every column using `.dtypes`, and count how many missing values each column has using `.isnull().sum()`.

In [35]:
df.dtypes
df.isnull().sum()
df.shape

(55500, 15)

### Question 3 — Unique Values
Find how many unique values are in the `Medical Condition` column, and print out what those unique values actually are.

In [15]:
df["Medical Condition"].unique()

<StringArray>
['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension', 'Arthritis']
Length: 6, dtype: str

### Question 4 — Selecting Columns
Create a new DataFrame called `patients` that contains only these columns: `Name`, `Age`, `Medical Condition`, and `Billing Amount`.

In [18]:
patients=df[["Name","Age","Medical Condition","Billing Amount"]]
patients

                    Name  Age Medical Condition  Billing Amount
0          Bobby JacksOn   30            Cancer    18856.281306
1           LesLie TErRy   62           Obesity    33643.327287
2            DaNnY sMitH   76           Obesity    27955.096079
3           andrEw waTtS   28          Diabetes    37909.782410
4          adrIENNE bEll   43            Cancer    14238.317814
...                  ...  ...               ...             ...
55495  eLIZABeTH jaCkSOn   42            Asthma     2650.714952
55496         KYle pEREz   61           Obesity    31457.797307
55497       HEATher WaNG   38      Hypertension    27620.764717
55498     JENniFER JOneS   43         Arthritis    32451.092358
55499       jAMES GARCiA   53         Arthritis     4010.134172

[55500 rows x 4 columns]

### Question 5 — Boolean Filtering
Filter the dataset to show only patients where `Medical Condition` is `"Diabetes"` **and** `Age` is greater than 50.

In [20]:
df[(df["Medical Condition"]=="Diabetes")&(df["Age"]>50)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal
66,ChRiStOPhER gOnzAlez,59,Male,B+,Diabetes,2019-11-21,Patricia Dunn,Rhodes-Carey,Medicare,10107.187651,368,Emergency,2019-12-08,Penicillin,Abnormal
82,SeaN jenniNGs,80,Female,AB-,Diabetes,2023-11-12,James Tucker,Clark-Johnson,Blue Cross,20257.544283,255,Elective,2023-12-12,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55409,WEslEY BarkEr,58,Male,O+,Diabetes,2020-06-22,Jonathan Cabrera,Long LLC,Cigna,44241.630103,324,Urgent,2020-07-05,Ibuprofen,Normal
55416,GrEG Bush,67,Male,B-,Diabetes,2021-09-26,Joshua Davis,Ltd Cox,Cigna,16097.163523,483,Emergency,2021-10-12,Paracetamol,Abnormal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,UnitedHealthcare,5271.154491,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959.491185,462,Urgent,2019-12-06,Lipitor,Abnormal
55439,cHRiStINE MCCARty,75,Male,AB+,Diabetes,2024-04-28,Gregory Pineda,Wu-Stark,Aetna,23720.022368,313,Emergency,2024-05-19,Penicillin,Abnormal

### Question 6 — Cleaning: Duplicates & Bad Values
This dataset has some issues hiding in it:
1. Remove exact duplicate rows using `drop_duplicates()`.
2. Some rows have a **negative** `Billing Amount`, which doesn't make sense for a hospital bill. Remove any rows where `Billing Amount` is less than 0.

Print the number of rows before and after, so you can see how many were removed.

In [41]:
df.duplicated().sum()
df.shape
df.drop_duplicates(inplace=True)
df=df[df["Billing Amount"]>0]

### Question 7 — Cleaning: Inconsistent Text
Look closely at the `Name` column — the capitalization is inconsistent (e.g. `"Bobby JacksOn"`, `"LesLie TErRy"`). Clean it so every name is properly title-cased (e.g. `"Bobby Jackson"`).

In [53]:
df["Name"]=df["Name"].str.strip().str.title()
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

### Question 8 — Feature Engineering with Dates
Convert `Date of Admission` and `Discharge Date` into real datetime columns using `pd.to_datetime()`. Then create a new column called `Length of Stay` that stores the number of days between admission and discharge for each patient.

In [58]:
df["Date of Admission"]=pd.to_datetime(df["Date of Admission"])
df["Discharge Date"]=pd.to_datetime(df["Discharge Date"])
df["Length of Stay"]=df["Discharge Date"]-df["Date of Admission"]
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2 days
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6 days
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15 days
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30 days
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20 days

### Question 9 — apply() with a Custom Function
Write a function called `get_age_group(age)` that returns:
- `"Child"` if age is 12 or under
- `"Teen"` if age is between 13 and 19
- `"Adult"` if age is between 20 and 59
- `"Senior"` if age is 60 or above

Then use `.apply()` to create a new column `Age Group` in `df` using this function.

In [60]:
def get_age_group(age):
    if age<12:
        return "child"
    elif age>=12 and age<=19:
        return "Teen"
    elif age>19 and age<=59:
        return "Adult"
    else:
        return "Senior"

df["Age Group"]=df["Age"].apply(get_age_group)
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2 days,Adult
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6 days,Senior
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15 days,Senior
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30 days,Adult
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20 days,Adult

### Question 10 — apply() with a Lambda
Using `.apply()` with a **lambda function**, create a new column called `High Bill` that stores `"Yes"` if a patient's `Billing Amount` is above the *average* billing amount of the whole dataset, and `"No"` otherwise.

In [63]:
df["High Bill"]=df["Billing Amount"].apply(lambda amount:"Yes" if amount>df["Billing Amount"].mean() else "no")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group,High Bill
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2 days,Adult,no
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6 days,Senior,Yes
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15 days,Senior,Yes
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30 days,Adult,Yes
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20 days,Adult,no

### Question 11 — Sorting
Sort the dataset by `Billing Amount` in descending order, and display the top 10 most expensive cases — just the `Name`, `Medical Condition`, and `Billing Amount` columns.

In [68]:
df.sort_values(by="Billing Amount",ascending=False,inplace=True)
df.iloc[0:11]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group,High Bill
36349,Todd Carrillo,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764.276736,209,Elective,2023-10-04,Ibuprofen,Normal,26 days,Adult,Yes
51313,Karen Kline,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive,14 days,Senior,Yes
34613,Karen Kline,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive,14 days,Senior,Yes
5735,David Sandoval,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52271.663747,228,Emergency,2019-11-11,Ibuprofen,Normal,9 days,Adult,Yes
7088,Kathryn Gonzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52211.852966,383,Urgent,2020-08-12,Paracetamol,Inconclusive,1 days,Teen,Yes
1574,Brett Marshall,42,Female,B+,Asthma,2021-11-10,Robert Hartman,PLC Garner,Aetna,52181.837792,140,Emergency,2021-11-17,Penicillin,Inconclusive,7 days,Adult,Yes
52826,Laurie Hood,43,Female,A-,Arthritis,2021-06-27,Brian Riley,Walker-Garcia,Cigna,52170.036854,306,Urgent,2021-06-29,Penicillin,Normal,2 days,Adult,Yes
6663,Laurie Hood,42,Female,A-,Arthritis,2021-06-27,Brian Riley,Walker-Garcia,Cigna,52170.036854,306,Urgent,2021-06-29,Penicillin,Normal,2 days,Adult,Yes
33117,Justin Clark,53,Female,AB+,Cancer,2019-05-30,Andrea Jones,Ruiz-Anthony,UnitedHealthcare,52154.237722,399,Urgent,2019-06-22,Aspirin,Normal,23 days,Adult,Yes
34368,Scott Powell,38,Female,B+,Cancer,2019-05-20,Stephen Hood PhD,George-Gonzalez,Cigna,52102.240889,155,Emergency,2019-05-29,Ibuprofen,Normal,9 days,Adult,Yes
13868,Cameron Hernandez,80,Male,B-,Cancer,2023-10-15,Joshua Rodgers,Rocha-Carter,Medicare,52092.669896,443,Emergency,2023-10-17,Aspirin,Abnormal,2 days,Senior,Yes

### Question 12 — GroupBy & Aggregation
Group the data by `Medical Condition` and find the **average** `Billing Amount` and the **average** `Length of Stay` (from Question 8) for each condition.

Based on your result: which medical condition has the highest average billing amount?

In [76]:
df.groupby(["Medical Condition"])[["Billing Amount"]].mean()
df.groupby(["Medical Condition"])[["Length of Stay"]].mean()

                           Length of Stay
Medical Condition
Arthritis         15 days 12:05:23.753665
Asthma            15 days 16:13:35.423598
Cancer            15 days 12:14:36.219712
Diabetes          15 days 10:18:27.752527
Hypertension      15 days 10:27:01.991019
Obesity           15 days 10:32:49.803878