In [1]:
import pandas as pd
import numpy as np

In [2]:
#Converting data to series
a=[1,2,3,4,5,6]
col1=pd.Series(a)
print(a)
print("-------")
print(col1)

[1, 2, 3, 4, 5, 6]
-------
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
#using array
c=np.array([1,2,3,4,5])
col2=pd.Series(c)
print(c)
print("--------")
print(col2)

[1 2 3 4 5]
--------
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
#creating using dictionary (very important)
d={"a":1,"b":2,"c":3,"d":4,"e":5}
col3=pd.Series(d)

print(col3)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
# Data Frames
df1=pd.DataFrame([d])
print(df1)
name=["Ayushman","Rishi","Ritika","Khushi"]
marks=[24,85,97,94]
df=pd.DataFrame({
    "name":name,
    "marks":marks
}
)

print(df)

   a  b  c  d  e
0  1  2  3  4  5
       name  marks
0  Ayushman     24
1     Rishi     85
2    Ritika     97
3    Khushi     94

In [6]:
#Loading real life data
employee=pd.read_csv("employees_100.csv")
employee

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [7]:
print(employee.head())
print("-----------------------------------------------------------------------------------------------")
print(employee.tail())
print("------------------------------------------------------------------------------------------------")
print(employee.sample())
print("--------------------------------------------------------------------------------------------------")
print(employee.shape)
print("--------------------------------------------------------------------------------------------------")
print(employee.dtypes)
print("---------------------------------------------------------------------------------------------------")
print(employee.info())
print("---------------------------------------------------------------------------------------------------")
print(employee.describe())

   employee_id            name    department       city   age salary  \
0          184    Swati Kapoor  Data Science    Kolkata  38.0  70719
1          154  Kavya Malhotra   engineering     Mumbai   NaN  77058
2          171    Manish Desai  Data Science  Hyderabad  23.0  69911
3          146        Neha Das   Engineering       Pune  28.0  69993
4          145       Isha Nair  Data Science        NaN  32.0  88216

   experience  performance_score  projects_completed joining_date
0           5                  5                   6   2021-07-02
1           1                  8                   8   2024-02-05
2           0                  6                  18   2019-04-24
3           3                  8                   1   2022-12-13
4           8                  8                  14   2019-11-25
-----------------------------------------------------------------------------------------------
    employee_id         name department     city   age salary  experience  \
95          161  Nikhil Nair  MARKETING  Chennai  22.0  55740           0
96          172   Neha Desai         HR  Chennai  22.0  52250           0
97          115   Neha Reddy  Marketing  Chennai  43.0    NaN          12
98          193  Priya Nayak         HR      NaN  23.0  56821           3
99          152  Kavya Joshi  Marketing    Delhi  44.0  69499          10

    performance_score  projects_completed joining_date
95                  5                  22   2020-04-22
96                  5                   7   2020-11-14
97                  4                  10   2019-06-06
98                  9                  16   2019-08-07
99                  7                   4   2022-03-25
------------------------------------------------------------------------------------------------
    employee_id        name department city   age salary  experience  \
91          175  Aman Nayak        NaN  NaN  27.0  69076           5

    performance_score  projects_completed joining_date
91                  5                  10   2019-09-15
--------------------------------------------------------------------------------------------------
(100, 10)
--------------------------------------------------------------------------------------------------
employee_id             int64
name                      str
department                str
city                      str
age                   float64
salary                    str
experience              int64
performance_score       int64
projects_completed      int64
joining_date              str
dtype: object
---------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB
None
---------------------------------------------------------------------------------------------------
       employee_id        age  experience  performance_score  \
count   100.000000  94.000000  100.000000           100.0000
mean    148.740000  30.861702    4.830000             5.7500
std      27.420637   6.483397    3.755279             1.7019
min     101.000000  22.000000    0.000000             2.0000
25%     125.750000  25.250000    2.000000             5.0000
50%     149.500000  31.000000    4.500000             6.0000
75%     171.250000  35.750000    8.000000             7.0000
max     196.000000  45.000000   17.000000            10.0000

       projects_completed
count          100.000000
mean             9.970000
std              5.332301
min              0.000000
25%              6.000000
50%              9.500000
75%             13.250000
max             24.000000

In [8]:
print(employee.isnull().sum())

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [9]:
#Selecting and filtering data

#selecting coloumn and also applying functions
employee["name"]
employee[["name","department"]].head()

#selecting rows
employee.head()
#There are index for individual rows so if you want to convert employee id to index then use :
print(employee.columns.tolist())

employee.head()
print("-----------------------")
print(employee.index.name)
#loc[]  will work on index we have made like employee_id
employee.loc[184]
employee.loc[[184,145]]
employee.loc[184:145]

['employee_id', 'name', 'department', 'city', 'age', 'salary', 'experience', 'performance_score', 'projects_completed', 'joining_date']
-----------------------
None

KeyError: 184

In [ ]:
#using iloc normal indexing
employee.iloc[0]
employee.iloc[1:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
employee.iloc[1:10][["name","city"]]

                        name       city
employee_id
154           Kavya Malhotra     Mumbai
171             Manish Desai  Hyderabad
146                 Neha Das       Pune
145                Isha Nair        NaN
140              Rahul Gupta  Hyderabad
123               Sneha Iyer  Hyderabad
181                Karan Rao        NaN
111              Kavya Singh      Delhi
101          Ananya Malhotra        NaN

In [ ]:
#boolean selection
employee["projects_completed"]>10
employee[employee["projects_completed"]>10].head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
119,Ritu Desai,Marketing,Pune,22.0,55321,0,6,18,2020-02-18

In [ ]:
#using logical operator combine condition
employee.head()

employee[(employee["age"]>20)&(employee["projects_completed"]>20)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22

In [ ]:
#default filtering methods
employee[employee["department"].isin(["Engineering","Data Science"])]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
156,Aditya Kapoor,Data Science,Kolkata,26.0,69765,0,2,4,2020-04-12
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05

In [ ]:
employee.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [ ]:
#Cleaning data


#removing all null value
df=employee.dropna()
df.shape
df.columns

df2=employee.dropna(subset=['city'])
df2.shape

(90, 9)

In [ ]:
#filling those values
employee["age"] = employee["age"].fillna(employee["age"].mean())
employee.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [ ]:
employee["salary"]=employee["salary"].str.replace(",","",regex=False)

In [ ]:
employee["salary"]=pd.to_numeric(employee["salary"],errors="coerce")
employee['salary']=employee["salary"].fillna(employee["salary"].median())

employee.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 184 to 152
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                100 non-null    str
 1   department          92 non-null     str
 2   city                90 non-null     str
 3   age                 100 non-null    float64
 4   salary              100 non-null    float64
 5   experience          100 non-null    int64
 6   performance_score   100 non-null    int64
 7   projects_completed  100 non-null    int64
 8   joining_date        100 non-null    str
dtypes: float64(2), int64(3), str(4)
memory usage: 11.9 KB

In [ ]:
#department
employee["department"].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [ ]:
employee["department"]=employee["department"].fillna(employee["department"].mode()[0])
employee["city"]=employee["city"].fillna(employee["city"].mode()[0])
employee.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [ ]:
#Handling duplicates
employee.duplicated(subset=["employee_id"]).sum()
employee[employee.duplicated(subset=["employee_id"])]

employee=employee.drop_duplicates(subset=["employee_id"])

employee.duplicated(subset=["employee_id"]).sum()
employee

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
#renaming a columns
employee.rename(columns={"name":"employee_name"})

,employee_id,employee_name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
employee["department"]=employee["department"].str.strip().str.lower()
employee["department"].unique()

<StringArray>
['data science', 'engineering', 'sales', 'hr', 'marketing', 'finance', nan]
Length: 7, dtype: str

In [ ]:
#modifying data and creating new coloumns

#lets add annual salary columns
employee["salary"]=pd.to_numeric(employee["salary"],errors="coerce")
employee["annual_salary"]=employee["salary"] * 12
employee.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,data science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,data science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,data science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0

In [ ]:
#apply function()
def categorize(num):
    if num>5:
        return "Experienced"
    else:
        return "Learner"

In [ ]:
employee["category"]=employee["experience"].apply(categorize)
employee.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,category
0,184,Swati Kapoor,data science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,data science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,data science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced

In [ ]:
#sorting and ranking 
employee["salary"]=pd.to_numeric(employee["salary"],errors="coerce")
employee["salary"]=employee["salary"].fillna(employee["salary"].mean())
employee.isnull().sum()
employee.sort_values(by="salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822.0,4,5,4,2022-06-24
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27
67,169,Swati Chatterjee,HR,Pune,33.0,49801.0,3,6,11,2021-08-20
7,181,Karan Rao,Marketing,NaN,22.0,50733.0,1,6,6,2020-04-05
40,150,Vivek Chatterjee,HR,Kolkata,22.0,51391.0,0,7,8,2019-11-20
...,...,...,...,...,...,...,...,...,...,...
92,187,Aditya Bose,Engineering,Bangalore,36.0,81112.0,7,4,9,2022-03-26
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25

In [ ]:
employee["department"]=employee["department"].fillna(employee["department"].mode()[0])

In [ ]:
employee.sort_values(by="employee_id",ascending=False).head()
employee["department"]=employee["department"].str.strip().str.title()
employee["department"].unique()

employee.sort_values(by=["department","salary"],ascending=[True,False])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05
59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24
...,...,...,...,...,...,...,...,...,...,...
48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26
44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27

In [ ]:
employee["age"]=employee["age"].fillna(employee["age"].mean())
employee["age"]=employee["age"].astype(int)

In [ ]:
#Grouping and Aggregation Function
employee.groupby("city")["age"].mean()

city
Bangalore    33.500000
Chennai      29.400000
Delhi        33.642857
Hyderabad    30.526316
Kolkata      27.692308
Mumbai       28.100000
Pune         31.642857
Name: age, dtype: float64

In [ ]:
employee.groupby(["department","city"])["salary"].min()

department    city
Data Science  Bangalore    64819.879518
              Delhi        76267.000000
              Hyderabad    69911.000000
              Kolkata      69765.000000
              Mumbai       78465.000000
              Pune         75498.000000
Engineering   Bangalore    77217.000000
              Chennai      62693.000000
              Delhi        64819.879518
              Hyderabad    84870.000000
              Kolkata      75226.000000
              Mumbai       64819.879518
              Pune         64819.879518
Finance       Bangalore    64819.879518
              Chennai      71889.000000
              Delhi        66422.000000
              Hyderabad    64819.879518
              Kolkata      58374.000000
              Mumbai       64112.000000
              Pune         60514.000000
Hr            Bangalore    59591.000000
              Chennai      52250.000000
              Delhi        55119.000000
              Hyderabad    48822.000000
              Kolkata      51391.000000
              Mumbai       64819.879518
              Pune         49801.000000
Marketing     Bangalore    60503.000000
              Chennai      55740.000000
              Delhi        56321.000000
              Hyderabad    49693.000000
              Kolkata      59186.000000
              Mumbai       56627.000000
              Pune         55321.000000
Sales         Chennai      57858.000000
              Delhi        63700.000000
              Hyderabad    52404.000000
              Kolkata      60015.000000
              Mumbai       52862.000000
Name: salary, dtype: float64