In [2]:
import pandas as pd

In [3]:
employee = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106],
    "name": ["Aman", "Riya", "Kabir", "Neha", "Arjun", "Sara"],
    "department": ["IT", "HR", "IT", "Sales", None, "HR"],
    "salary": [50000, 40000, 60000, None, 45000, 40000],
    "experience": [2, 1, 4, 3, 2, 1]
})

In [4]:
# Q1. Display the first 5 rows.
employee.head()

   employee_id   name department   salary  experience
0          101   Aman         IT  50000.0           2
1          102   Riya         HR  40000.0           1
2          103  Kabir         IT  60000.0           4
3          104   Neha      Sales      NaN           3
4          105  Arjun        NaN  45000.0           2

In [5]:
# Q2. Print the number of rows and columns.
print(employee.shape)

(6, 5)

In [6]:
# Q3. Display only the name and salary columns.
employee[["name","salary"]]

    name   salary
0   Aman  50000.0
1   Riya  40000.0
2  Kabir  60000.0
3   Neha      NaN
4  Arjun  45000.0
5   Sara  40000.0

In [7]:
# Q4. Find employees whose salary is greater than 45,000.
employee[employee["salary"]>45000]

   employee_id   name department   salary  experience
0          101   Aman         IT  50000.0           2
2          103  Kabir         IT  60000.0           4

In [8]:
#Q5. Find all rows where department is missing.
employee.loc[employee["department"].isnull()]

   employee_id   name department   salary  experience
4          105  Arjun        NaN  45000.0           2

In [9]:
#Fill missing salaries with the average salary.
employee["salary"]=employee["salary"].fillna(employee["salary"].mean())

In [10]:
#Display employees in descending order of salary.
employee.sort_values(by="salary",ascending=False)

   employee_id   name department   salary  experience
2          103  Kabir         IT  60000.0           4
0          101   Aman         IT  50000.0           2
3          104   Neha      Sales  47000.0           3
4          105  Arjun        NaN  45000.0           2
1          102   Riya         HR  40000.0           1
5          106   Sara         HR  40000.0           1

In [11]:
# Find the average salary of each department.
employee.groupby("department")["salary"].mean()

department
HR       40000.0
IT       55000.0
Sales    47000.0
Name: salary, dtype: float64

In [12]:
#Count employees in each department, including missing departments.
employee.groupby("department")["employee_id"].count()

department
HR       2
IT       2
Sales    1
Name: employee_id, dtype: int64

In [13]:
#Make employee_id the index and verify the result.
employee.set_index("employee_id")

              name department   salary  experience
employee_id
101           Aman         IT  50000.0           2
102           Riya         HR  40000.0           1
103          Kabir         IT  60000.0           4
104           Neha      Sales  47000.0           3
105          Arjun        NaN  45000.0           2
106           Sara         HR  40000.0           1

In [14]:
#Q11. Display the last 3 rows of the DataFrame.

employee.iloc[-3::1]

   employee_id   name department   salary  experience
3          104   Neha      Sales  47000.0           3
4          105  Arjun        NaN  45000.0           2
5          106   Sara         HR  40000.0           1

In [15]:
# Display the column names as a Python list.
employee.columns

Index(['employee_id', 'name', 'department', 'salary', 'experience'], dtype='str')

In [16]:
#Select employees whose experience is at least 2 years.
employee[employee["experience"]>=2]

   employee_id   name department   salary  experience
0          101   Aman         IT  50000.0           2
2          103  Kabir         IT  60000.0           4
3          104   Neha      Sales  47000.0           3
4          105  Arjun        NaN  45000.0           2

In [17]:
#Select employees from the IT department who have a salary above 50,000.
employee[(employee["department"]=="IT") & (employee["salary"]>50000)]

   employee_id   name department   salary  experience
2          103  Kabir         IT  60000.0           4

In [18]:
#Count the missing values in each column.
employee.isnull().sum()

employee_id    0
name           0
department     1
salary         0
experience     0
dtype: int64

In [19]:
# Remove rows containing any missing values without modifying the original DataFrame.
df=employee.dropna()
df

   employee_id   name department   salary  experience
0          101   Aman         IT  50000.0           2
1          102   Riya         HR  40000.0           1
2          103  Kabir         IT  60000.0           4
3          104   Neha      Sales  47000.0           3
5          106   Sara         HR  40000.0           1

In [20]:
#. Fill missing department values with 'Unknown'.
employee["department"]=employee["department"].fillna("unknown")

In [21]:
employee.isnull().sum()

employee_id    0
name           0
department     0
salary         0
experience     0
dtype: int64

In [22]:
#Rename the salary column to annual_salary
employee.rename(columns={"salary": "annual_salary"}, inplace=True)
employee

   employee_id   name department  annual_salary  experience
0          101   Aman         IT        50000.0           2
1          102   Riya         HR        40000.0           1
2          103  Kabir         IT        60000.0           4
3          104   Neha      Sales        47000.0           3
4          105  Arjun    unknown        45000.0           2
5          106   Sara         HR        40000.0           1

In [23]:
#Find the employee with the highest salary, ignoring missing salaries.
employee[employee["annual_salary"]==employee["annual_salary"].max()]

   employee_id   name department  annual_salary  experience
2          103  Kabir         IT        60000.0           4

In [24]:
#Calculate the minimum, maximum, and average experience.
print(employee["experience"].min())
print(employee["experience"].max())
print(employee["experience"].mean())

1
4
2.1666666666666665

In [25]:
# Q21. Select employees with experience between 1 and 3 years, inclusive
employee[employee["experience"].isin([1,3])]

   employee_id  name department  annual_salary  experience
1          102  Riya         HR        40000.0           1
3          104  Neha      Sales        47000.0           3
5          106  Sara         HR        40000.0           1

In [26]:
#Display employees whose names start with the letter 'A'.
employee[employee["name"].str.startswith("A")]

   employee_id   name department  annual_salary  experience
0          101   Aman         IT        50000.0           2
4          105  Arjun    unknown        45000.0           2

In [27]:
#Select employees who belong to either IT or HR.
employee[employee["department"].isin(["HR","IT"])]

   employee_id   name department  annual_salary  experience
0          101   Aman         IT        50000.0           2
1          102   Riya         HR        40000.0           1
2          103  Kabir         IT        60000.0           4
5          106   Sara         HR        40000.0           1

In [28]:
#Display the name and department of employees whose annual salary is missing.
employee.loc[
    employee["annual_salary"].isna(),
    ["name", "department"]
]

Empty DataFrame
Columns: [name, department]
Index: []

In [29]:
#Display the third and fourth rows using iloc.
employee.iloc[[3,4]]

   employee_id   name department  annual_salary  experience
3          104   Neha      Sales        47000.0           3
4          105  Arjun    unknown        45000.0           2

In [30]:
import pandas as pd

sales = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "customer": [
        "Aman", "Riya", "Kabir", "Neha", "Aman",
        "Sara", "Riya", "Arjun", "Neha", "Kabir"
    ],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune", None,
        "Mumbai", "Delhi", "Pune", "Delhi", "Mumbai"
    ],
    "category": [
        "Electronics", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture"
    ],
    "amount": [
        25000, 1500, 18000, None, 2500,
        32000, 7000, 3000, 22000, 9000
    ],
    "quantity": [2, 3, 1, 2, 5, 1, 2, 4, 2, 1],
    "rating": [5, 4, 5, 3, None, 5, 4, 3, 4, 5]
})

In [31]:
#Q26. Replace missing values in `amount` with 0.
sales["amount"]=sales["amount"].fillna(0)
sales["amount"]

0    25000.0
1     1500.0
2    18000.0
3        0.0
4     2500.0
5    32000.0
6     7000.0
7     3000.0
8    22000.0
9     9000.0
Name: amount, dtype: float64

In [32]:
#Q27. Fill missing `city` values with 'Unknown' and update the DataFrame.
sales["city"]=sales["city"].fillna("unkown")

In [33]:
#Q28. Create a `total_items` column equal to `quantity` multiplied by 2.
sales["total_item"]=sales["quantity"]*2
sales.head()

,order_id,customer,city,category,amount,quantity,rating,total_item
0,101,Aman,Delhi,Electronics,25000.0,2,5.0,4
1,102,Riya,Mumbai,Clothing,1500.0,3,4.0,6
2,103,Kabir,Delhi,Electronics,18000.0,1,5.0,2
3,104,Neha,Pune,Furniture,0.0,2,3.0,4
4,105,Aman,unkown,Clothing,2500.0,5,NaN,10

In [34]:
# Q29. Create a `discounted_amount` column equal to 90% of `amount`.
sales["discounted_amount"]=sales["amount"]*0.90
sales.head()

,order_id,customer,city,category,amount,quantity,rating,total_item,discounted_amount
0,101,Aman,Delhi,Electronics,25000.0,2,5.0,4,22500.0
1,102,Riya,Mumbai,Clothing,1500.0,3,4.0,6,1350.0
2,103,Kabir,Delhi,Electronics,18000.0,1,5.0,2,16200.0
3,104,Neha,Pune,Furniture,0.0,2,3.0,4,0.0
4,105,Aman,unkown,Clothing,2500.0,5,NaN,10,2250.0

In [35]:
#Q30. Drop the `rating` column into a new DataFrame without changing `sales`
sales["rating"]=sales["rating"].fillna(sales["rating"].mean())
rating2=sales.drop("rating", axis=1, inplace=False)

In [36]:
#Q31. Calculate the total sales amount, ignoring missing values.
sales_amount=sales["amount"].sum()
sales_amount

np.float64(120000.0)

In [37]:
#Q32. Count the number of orders in each category.
sales.groupby("category")["order_id"].count()

category
Clothing       3
Electronics    4
Furniture      3
Name: order_id, dtype: int64

In [38]:
#Q33. Find the average amount for each category.
sales.groupby("category")["amount"].mean()

category
Clothing        2333.333333
Electronics    24250.000000
Furniture       5333.333333
Name: amount, dtype: float64

In [39]:
#Find the maximum quantity for each city.
sales.groupby("city")["quantity"].max()

city
Delhi     2
Mumbai    3
Pune      4
unkown    5
Name: quantity, dtype: int64

In [40]:
#Q35. Sort orders by category alphabetically, then amount from highest to lowest.
sales.sort_values(by=["category","amount"],ascending=False)

,order_id,customer,city,category,amount,quantity,rating,total_item,discounted_amount
9,110,Kabir,Mumbai,Furniture,9000.0,1,5.000000,2,8100.0
6,107,Riya,Delhi,Furniture,7000.0,2,4.000000,4,6300.0
3,104,Neha,Pune,Furniture,0.0,2,3.000000,4,0.0
5,106,Sara,Mumbai,Electronics,32000.0,1,5.000000,2,28800.0
0,101,Aman,Delhi,Electronics,25000.0,2,5.000000,4,22500.0
8,109,Neha,Delhi,Electronics,22000.0,2,4.000000,4,19800.0
2,103,Kabir,Delhi,Electronics,18000.0,1,5.000000,2,16200.0
7,108,Arjun,Pune,Clothing,3000.0,4,3.000000,8,2700.0
4,105,Aman,unkown,Clothing,2500.0,5,4.222222,10,2250.0
1,102,Riya,Mumbai,Clothing,1500.0,3,4.000000,6,1350.0

In [41]:
#Q36. Find the second-highest distinct order amount.
sales.sort_values(by="amount",ascending=False).iloc[2]

order_id                     109
customer                    Neha
city                       Delhi
category             Electronics
amount                   22000.0
quantity                       2
rating                       4.0
total_item                     4
discounted_amount        19800.0
Name: 8, dtype: object

In [42]:
#Q37. Find orders whose amount is greater than the average amount.
sales[sales["amount"]>sales["amount"].mean()]

,order_id,customer,city,category,amount,quantity,rating,total_item,discounted_amount
0,101,Aman,Delhi,Electronics,25000.0,2,5.0,4,22500.0
2,103,Kabir,Delhi,Electronics,18000.0,1,5.0,2,16200.0
5,106,Sara,Mumbai,Electronics,32000.0,1,5.0,2,28800.0
8,109,Neha,Delhi,Electronics,22000.0,2,4.0,4,19800.0

In [43]:
#Q38. Identify duplicate rows based on the customer column.
sales["customer"].duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
7    False
8     True
9     True
Name: customer, dtype: bool

In [ ]:
#Q40. Create a `sales_rank` column, ranking orders by amount from highest to lowest
sales["sales_rank"]=sales.rank()
sales.head()

,order_id,customer,city,category,amount,quantity,rating,total_item,discounted_amount
0,101,Aman,Delhi,Electronics,25000.0,2,5.000000,4,22500.0
1,102,Riya,Mumbai,Clothing,1500.0,3,4.000000,6,1350.0
2,103,Kabir,Delhi,Electronics,18000.0,1,5.000000,2,16200.0
3,104,Neha,Pune,Furniture,0.0,2,3.000000,4,0.0
4,105,Aman,unkown,Clothing,2500.0,5,4.222222,10,2250.0

In [48]:
# Select orders from Delhi or Mumbai where the amount is greater than 10,000.
sales[(sales["city"].isin(["Delhi","Mumbai"]))& (sales["amount"]>10000)]

,order_id,customer,city,category,amount,quantity,rating,total_item,discounted_amount
0,101,Aman,Delhi,Electronics,25000.0,2,5.0,4,22500.0
2,103,Kabir,Delhi,Electronics,18000.0,1,5.0,2,16200.0
5,106,Sara,Mumbai,Electronics,32000.0,1,5.0,2,28800.0
8,109,Neha,Delhi,Electronics,22000.0,2,4.0,4,19800.0

In [54]:
#Q42. Display the customer and amount for orders with a rating of 5, sorted by amount in descending order.
sales[sales["rating"]==5][["customer","amount"]].sort_values(by="amount",ascending=False)

  customer   amount
5     Sara  32000.0
0     Aman  25000.0
2    Kabir  18000.0
9    Kabir   9000.0

In [56]:
#Q43. Find orders where either the city or rating is missing.
sales[(sales["city"].isnull())|(sales["rating"].isnull())]
sales.isnull().sum()

order_id             0
customer             0
city                 0
category             0
amount               0
quantity             0
rating               0
total_item           0
discounted_amount    0
dtype: int64

In [57]:
#Create a summary with total amount, average amount, and order count for each category.

sales.groupby("category").agg(
    total_amount=("amount","sum"),
    average_amount=("amount","mean")
)

             total_amount  average_amount
category
Clothing           7000.0     2333.333333
Electronics       97000.0    24250.000000
Furniture         16000.0     5333.333333